"""add saved_lots table

Revision ID: b945ddfdc617
Revises: 9e365dca24cf
Create Date: 2026-10-06 15:47:11.206437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b945ddfdc617'
down_revision: Union[str, Sequence[str], None] = '9e365dca24cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('site', sa.Integer(), nullable=False),
    sa.Column('base_site', sa.String(length=16), nullable=True),
    sa.Column('salvage_id', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.String(), nullable=True),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('price_new', sa.Integer(), nullable=True),
    sa.Column('price_future', sa.Integer(), nullable=True),
    sa.Column('current_bid', sa.Integer(), nullable=True),
    sa.Column('auction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_priced', sa.Integer(), nullable=True),
    sa.Column('cost_repair', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('auction_type', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('damage_pr', sa.String(), nullable=True),
    sa.Column('damage_sec', sa.String(), nullable=True),
    sa.Column('loss', sa.String(), nullable=True),
    sa.Column('keys', sa.String(), nullable=True),
    sa.Column('odobrand', sa.String(), nullable=True),
    sa.Column('fuel', sa.String(), nullable=True),
    sa.Column('drive', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('presale_status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('vin', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('engine_size', sa.Double(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('location_old', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('document_old', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('is_buynow', sa.Boolean(), nullable=True),
    sa.Column('iaai_360', sa.String(), nullable=True),
    sa.Column('copart_exterior_360', sa.JSON(), nullable=True),
    sa.Column('copart_interior_360', sa.String(), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('link_img_hd', sa.JSON(), nullable=True),
    sa.Column('link_img_small', sa.JSON(), nullable=True),
    sa.Column('is_offsite', sa.Boolean(), nullable=True),
    sa.Column('location_offsite', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('seller_type_model', sa.String(), nullable=True),
    sa.Column('seller_type', sa.String(), nullable=True),
    sa.Column('seller_detailed_type', sa.String(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('vehicle_score', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('branch_number', sa.String(), nullable=True),
    sa.Column('branch_link', sa.String(), nullable=True),
    sa.Column('title_brand', sa.String(), nullable=True),
    sa.Column('airbag', sa.String(), nullable=True),
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('odometer_index', sa.String(), nullable=True),
    sa.Column('timed_auction_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_tbo', sa.Boolean(), nullable=True),
    sa.Column('is_title_pending', sa.Boolean(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('lane', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('copart_yard_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_lots_lot_id_site', 'saved_lots', ['lot_id', 'site'], unique=True)
    op.create_index(op.f('ix_saved_lots_vin'), 'saved_lots', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_lots_vin'), table_name='saved_lots')
    op.drop_index('ix_saved_lots_lot_id_site', table_name='saved_lots')
    op.drop_table('saved_lots')
    # ### end Alembic commands ###
